"""Markdown report generator."""

from __future__ import annotations

from pathlib import Path
from maturity.model.evidence import MaturityAssessment


def generate_report(assessment: MaturityAssessment) -> str:
    """Generate a full markdown maturity report."""
    domain_rows = "\n".join(
        f"| {d.domain} | {d.assessed_level}/5 | {d.confidence} | {', '.join(d.strengths[:2]) or '-'} |"
        for d in assessment.domains
    )
    gaps_list = "\n".join(f"- {g}" for g in assessment.critical_gaps) or "- None identified"
    strengths_list = "\n".join(f"- {s}" for s in assessment.top_strengths) or "- None identified"
    roadmap_list = "\n".join(f"{i+1}. {r}" for i, r in enumerate(assessment.roadmap)) or "- No roadmap generated"

    return f"""# Platform Engineering Maturity Report

**Organization**: {assessment.org or "Engineering organization"}
**Assessed**: {assessment.assessed_at[:10]}
**Industry**: {assessment.industry}
**Overall Level**: {assessment.overall_level}/5 — {assessment.level_name}
**Overall Score**: {assessment.overall_score:.2f}/5.0

---

## Executive summary

{assessment.narrative}

---

## Domain scores

| Domain | Level | Confidence | Strengths |
|--------|-------|------------|-----------|
{domain_rows}

---

## Top strengths

{strengths_list}

## Critical gaps

{gaps_list}

## Recommended roadmap

{roadmap_list}

---

*Generated by platform-maturity-model — github.com/brianpelow/platform-maturity-model*
"""


def save_report(assessment: MaturityAssessment, output_dir: str = "reports") -> Path:
    """Save a maturity report to disk."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    filename = f"maturity-report-{assessment.assessed_at[:10]}.md"
    path = out / filename
    path.write_text(generate_report(assessment))
    return path